# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- v2
- main

strategy:
  matrix:
    linux_node_lts_16:
      imageName: 'ubuntu-22.04'
      node_version: 16.x
    linux_node_lts_18_min_version:
      imageName: 'ubuntu-22.04'
      node_version: 18.12.0
    linux_node_lts_18:
      imageName: 'ubuntu-22.04'
      node_version: 18.x
    mac_node_lts_18:
      imageName: 'macos-12'
      node_version: 18.x
    windows_node_lts_18:
      imageName: 'windows-2022'
      node_version: 18.x
    linux_node_current:
      imageName: 'ubuntu-22.04'
      node_version: 19.x
    mac_node_current:
      imageName: 'macos-12'
      node_version: 19.x
    windows_node_current:
      imageName: 'windows-2022'
      node_version: 19.x

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: Install Node.js

- script: npm ci
  displayName: Install Dependencies

- script: npm ls --prod
  displayName: Check for missing / extraneous Dependencies

- script: npm run test-azure
  displayName: Run Tests

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'

- task: PublishCodeCoverageResults@1
  displayName: Publish Test Coverage Results
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

- script: npm run coverage
  displayName: Run Test Natively in Case of Failures
  condition: failed()
